### ISSUE TITLE
Upgraded from 0.4.1 to 0.5.1 and menu is not shown anymore if absolute position is used 

### ISSUE THREAD

**Issue by opensw** [react-native-menu/menu#152]
Hello there, I have just upgraded from 0.4.1 to 0.5.1 but now the menu is not shown anymore if the absolute position is used. The following component is passed to another component like children (to a custom Video Player)

```
<View
                style={
                    position: "absolute",
                    top: 0,
                    bottom: 0,
                    left: 0,
                    right: 0,
                    width: 40,
                }
>
                <MenuView
                    isAnchoredToRight={true}
                    onPressAction={({ nativeEvent }) => {
                        if (isDisabled === true) {
                            return;
                        }

                        switch (nativeEvent.event) {
                            case EnumItemActions.duplicate:
                                event.duplicateItem({id: item.id});
                                break;
        
                            case EnumItemActions.sendToEvent:
                                setItemToSend(item.id);
                                break;
        
                            case EnumItemActions.delete:
                                setItemIdToDelete(item.id);
                                break;
                        }
                    }}
                    actions={isDisabled === false ? [
                    {
                        id: EnumItemActions.duplicate,
                        title: 'Duplicate',
                    },
                    {
                        id: EnumItemActions.sendToEvent,
                        title: 'Send to Event',
                    },
                    {
                        id: EnumItemActions.delete,
                        title: 'Delete',
                    },
                    ] : []}
                >
                    <Icon
                        name="more-vert"
                        containerStyle={{ alignSelf: "center" }}
                        disabled={isDisabled === true}
                        color={iconColor}
                    />
                </MenuView>
            </View>
```

**Comment by mateusz1913** [comment]
![IMG_0161](https://user-images.githubusercontent.com/25980166/124921929-3d1b9280-dff9-11eb-80b2-4e81a9dd606c.jpg)

Hi @opensw , I tried to reproduce your case on repo's example app - result on above screenshot. The container view area with absolute position has yellow background. Menu component is overlapping that container view and when I try to tap on overlapped red area, there is no menu. However, when I tap on the right side, within yellow area bounds, it is working as expected.
I would say that it is rather styling issue on your side, than some issue on lib side. Try to increase your container's view area to make menu component not overlapping its parent.

If you want to reproduce it on example's repo here is diff:

```sh
diff --git a/example/src/App.tsx b/example/src/App.tsx
index ba3a574..363212d 100644
--- a/example/src/App.tsx
+++ b/example/src/App.tsx
@@ -170,9 +170,16 @@ export const App = () => {
 
 const styles = StyleSheet.create({
   container: {
-    flex: 1,
-    alignItems: 'center',
-    justifyContent: 'center',
+    // flex: 1,
+    // alignItems: 'center',
+    // justifyContent: 'center',
+    position: 'absolute',
+    backgroundColor: 'yellow',
+    top: 0,
+    left: 0,
+    right: 0,
+    bottom: 0,
+    width: 40,
   },
   button: {

```

**Comment by opensw** [comment]
Hi @mateusz1913,
   I have tried but the issue persists.

In 0.4.1 it works like expected, in 0.5.1 (I did not change anything in the code, I have just upgraded the library) it does not work.

I am using flex-box to arrange the components:
- Violet color, the main container (TouchableOpacity component)
- Yellow color, the container of the icon (View component)
- Green color,  icon component to open the menu (Icon component from react-native-elements)

I am guessing, there is an issue with the combination of flex-box and absolute position.

Let me know if you need more details, thank you for any help

![Screenshot_20210709-110216_HighLights](https://user-images.githubusercontent.com/729329/125054984-0ef48c00-e0a7-11eb-955a-e68d37b06145.jpg)
![Screenshot_20210709-110207_HighLights](https://user-images.githubusercontent.com/729329/125054986-1025b900-e0a7-11eb-9b75-7e7dc2b8cbbb.jpg)

**Comment by mateusz1913** [comment]
@opensw in 0.5.0 there was long press support introduced, maybe it is not working well with absolute position in android

**Comment by opensw** [comment]
At the moment I will stick with the 0.4.1 version. Let me know if you need more help to reproduce the issue, if you need I can do some other tests too

**Comment by mateusz1913** [comment]
Yeah, some minimal repo could make it easier to reproduce that (especially all style values for violet, yellow and green containers) - I tried to check which taps are detected in android native code, and as long as tap is taking place inside parent container ("yellow" one in your case), it should be working

**Comment by opensw** [comment]
OK, I will try tomorrow to arrange a minimal example

**Comment by opensw** [comment]
Hi, from here you can play with a demo https://github.com/opensw/BugDemoReactNativeMenu

In 0.4.1 the menu is working, in 0.5.1 it is not working. The project is configured for Android, for iOS you need to install https://github.com/oblador/react-native-vector-icons (just drag and drop the required fonts on Xcode like described in the installation section).

Please, do not remove any components from the code (style too), some of them seem useless but in my real code they are used for other stuff (it is just to give you the exact code structure that I am using in my real code).

How to upgrade:
- Stop metro on your development machine
- Uninstall the App from your phone
- Change in package.json the "@react-native-menu/menu": "^0.4.1" to "@react-native-menu/menu": "^0.5.1"
- Use my script install.sh
- Start metro on your development machine `npm start -- --reset-cache`
- Start the app like usually `npx react-native...`

![Screenshot_20210716-090031_DemoReactNativeMenu](https://user-images.githubusercontent.com/729329/125909723-77ac3763-639f-451c-91fe-d99f179fdb9c.jpg)
![Screenshot_20210716-090736_DemoReactNativeMenu](https://user-images.githubusercontent.com/729329/125909725-22252abc-531d-4a60-a536-f364419b8d1c.jpg)

**Comment by mateusz1913** [comment]
Thanks @opensw , that was exactly what I was looking for.

I built that repo, but in my case I wasn't able to reproduce your issue. My repro steps (for v0.5.1) were:
1) downloading repo and installing deps (react-native-safe-area-context was also mandatory)
2) opening android project and adding some logs inside menu library:
- log after 36. line (gesture detector listener)
```
android.util.Log.d("MenuView", "onSingleTapConfirmed, ${e?.action}")
```
- log after 45. line (onInterceptTouchEvent)
```
android.util.Log.d("MenuView", "onInterceptTouchEvent, ${ev?.action}")
```
- log after 50. line (onTouchEvent)
```
android.util.Log.d("MenuView", "onTouchEvent, ${ev?.action}")
```

When menu is opened, logs should be displayed in logcat in order:

```
onInterceptTouchEvent, 0
onTouchEvent, 0
onTouchEvent, 1
onSingleTapConfirmed, 0
```

--------

I wasn't able to reproduce that with provided setup & styles

--------

The only case when tapping on menu component is not triggering menu display is when:
- menu component is overflowing its parent
- user taps on **overflowed** part (in that case on part which overflows yellow container)

Maybe @Naturalclar will be able to reproduce your problem (also you can try to apply styles directly to `MenuView` instead of an icon)

**Comment by opensw** [comment]
Hi @mateusz1913 , I had updated the repo with react-native-safe-area-context. On my Samsung A21s, the issue persists. I will try in the next few days to debug better what is going on.

Thank you
